name: WDIO-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      
      - uses: actions/checkout@v3

      # Instalar Geckodriver - especificamos una versión fija
      - name: Install Geckodriver
        run: |
          GECKODRIVER_VERSION="v0.33.0"
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps
